### ISSUE TITLE
Улучшение структуры проекта

### ISSUE THREAD

**Issue by foobar1643** [someApprentice/phpClub#1]
### index.php
Тут используем [Front Controller](https://en.wikipedia.org/wiki/Front_controller), с помощью URL Rewrite все запросы направляем на index.php. В этом файле подключаем Bootstrap файл, главная задача которого - вернуть DI контейнер с нужными нам сервисами. Из суперглобала $_SERVER создаем абстракцию над HTTP запросом экземпляр класса Request, который реализован согласно PSR-7. Создаем экземпляр класса Application, который в конструктор принимает DI контейнер, вызываем Application::run($request), если все отработало удачно, метод Application::run должен вернуть экземпляр класса Response (PSR-7), _содержание которого мы отдаем пользователю_.

### Application
Реализует основную логику приложения, скрывает в себе объект Router, принцип работы которого будет описан ниже. _Имеет публичные методы вроде Application::addRoute($method, $path, $callable), которые добавляют роуты, инкапсулируя при этом сам роутер._ При вызове метода Application::run($request) передает PSR-7 запрос в роутер, и в случае успеха получает от роутера callable, который привязан к роуту (контроллер). Привязанный callable может быть методом класса или анонимной функцией. Обязательное условие для валидности контроллера - он всегда обязан принимать экземпляры PSR-7 Request и Response в качестве параметров, возвращать он должен экземпляр PSR-7 Response (такой подход позволит реализовать Middleware-стэк, на всякий случай, даже если у нас его и не будет). Валидировать привязанный callable можно используя [Reflection API](http://php.net/manual/en/book.reflection.php), или _описав контроллер приложения интерфейсом_ (тогда теряем возможность использовать анонимные функции в качестве контроллера, но реализация получается более понятной и надежной). _Так же следует подумать каким образом сделать DI контейнер доступным в контроллерах_ (тут у меня есть один вариант, нужно потестить). Общая идея контроллера - получить на вход экземпляры Request, Response, что-нибудь сделать, заполнить Response, и вернуть его.

### Router
Роутер будет описан интерфейсом, реализация будет использовать регулярные выражения, будет поддержка плейсхолдеров. Сами роуты являются сущностью (класс Route), которые в свою очередь хранятся в коллекции RouteCollection. Экземпляр класса Router содержит в себе RouteCollection, в котором мы храним все зарегистрированные роуты. Так как мы используем регулярные выражения для поиска роутов, нам нужно будет при каждом вызове метода Router::routeRequest обходить всю коллекцию роутов циклом, и проверять каждый роут на совпадения с URL, который пришел в запросе. Это дает очень сильную просадку в производительности, если у нас будет много роутов. Для решения этой проблемы можно использовать [nikic/FastRoute ](https://github.com/nikic/FastRoute). Принцип работы данного решения и почему оно быстрое можно [почитать тут](http://nikic.github.io/2014/02/18/Fast-request-routing-using-regular-expressions.html) (довольно интересная статья). В случае если роута для данного URL не нашлось, бросаем RouteNotFoundException, в конструктор которого передаем URL, по которому был сделан реквест и еще какую-нибудь полезную информацию. В случае если запрос был сделан другим методом (например роут создан как POST, а запрашивают методом GET), _выбрасываем MethodNotAllowedException_.

### View
Так как у нас теперь используются абстракции над HTTP запросом и ответом, просто отдать пользователю HTML разметку не получится. Шаблоны нужно рендерить в тело экземпляра класса Response, содержание которого мы будем отдавать клиенту. Для этого будет отдельный класс, View, который будет сервисом в DI контейнере. Шаблонизатор я не думаю что тут нужен, хватит обычного PHP. Для рендеринга шаблонов класс View будет использовать include, для того чтобы ничего не отдать клиенту раньше времени, нужно производить [манипуляции с буфером вывода PHP](http://php.net/manual/en/ref.outcontrol.php).

### Обработка ошибок
При любой ошибке в приложении должно бросаться исключение. При инициализации приложения мы [задаем обработчик исключений](http://php.net/manual/en/function.set-exception-handler.php), который будет разбирать пришедшее исключение (его тип, код ошибки, сообщение об ошибке, что-нибудь еще) и показывать пользователю заглушку в зависимости от того как был запущен скрипт (если произошло исключение в парсере, запущенном через командную строку, тут можно совсем ничего не делать, сам PHP достаточно понятно выводит исключения в консоль). Для заглушки нужен отдельный шаблон (тут нужно подумать как именно его рендерить и отдавать пользователю), так же будет два режима - production и development, в дев режиме мы получаем больше информации об ошибке (тип исключения, в каком файле произошло, на какой строке, стак трейс и прочее), в прод режиме мы всю эту информацию скрываем и оставляем только экран с текстом. _Так же [нужно подумать](https://en.wikipedia.org/wiki/Strategy_pattern) о разных сценариях поведения обработчика при разных типах исключений (ошибка 404 у нас тоже исключение)._

### Структура реализации PSR-7
Описания самих интерфейсов можно [почитать тут](http://www.php-fig.org/psr/psr-7/), в реализации будет абстрактный класс Message, от которого наследуем Request и Response, заголовки запроса и ответа будем хранить в классе Headers, который наследуем от Collection, для всех манипуляций с куками используем коллекцию Cookies, концепт которой [описан тут](https://github.com/foobar1643/student-list/blob/master/src/Http/Cookies.php). Для хранения и манипуляций с телом ответа используем класс Stream, который в свою очередь использует [стандартные средства для работы с потоками в PHP](http://php.net/manual/en/ref.filesystem.php).

## Итог
Тут описывалась только структура, которую мы будем использовать для веб части приложения, это в первую очередь сам архив, и возможно REST API для удобного чтения архива на телефоне (например у дашчана [есть отличная документация](https://github.com/Mishiranu/Dashchan-Extensions/wiki/Extension-devepment-tutorial) по API и написанию расширения, я бы написал расширение, которое позволило бы читать архив через дашчан). Не стоит забывать что у нас так же будут и парсеры (именно парсеры, если мы хотим хранить совсем все треды с самого начала, вроде бы у ОПа они есть в .html формате), которые работают как CLI скрипты. Архитектуру нужно строить таким образом, чтобы жизненный цикл CLI версии, и версии которую запросили в браузере минимально отличался. Это облегчит нам работу и не нужно будет по два раза писать одну и ту же логику. У меня есть некоторые соображения на эту тему, но я никогда не делал подобных вещей, поэтому тут нужно будет дополнительно подумать. Так же, возможно стоит распределить все .php файлы по соответствующим папкам и использовать более правильный неймспейс (формата vendor/package-name, в нашем случае это SomeApprentice/PhpClub, хотя длинновато получается). Все что тут описывалось - просто как черновик, если есть какие-нибудь предложения или замечания по структуре - можно их обсудить в комментариях. _Курсивом_ выделил сомнительные вещи, над которыми нужно подумать, по этому поводу я позже отпишу сюда же, как появится свободное время.

**Comment by kubk** [comment]
Согласен, что структуру проекта не помешает пересмотреть. По поводу предложенной в issue структуры - она очень напоминает Slim, не проще ли его использовать? Slim тоже внутри использует nikic/FastRoute, не нужно думать о том, как прокинуть контейнер в контроллер и писать/тестировать свою реализацию PSR7, когда уже есть готовая и оттестированная. Таким образом можно возложить рутину на фреймворк и сконцентрироваться на том, что должно делать приложение.

**Comment by foobar1643** [comment]
Если проблем с использованием фреймворка нет, конечно лучше использовать его. Нужно потестить, можно ли слимовский Application использовать в CLI режиме. Я последний раз когда смотрел, у них в метод Application::run можно было передать булевую переменную, которая поменяет поведение метода - вместо отдачи пользователю ответа, метод вернет готовый объект Response. Это потенциально позволит использовать один и тот же Application как для веба, так и для CLI скриптов, но это нужно тестить. Еще неплохо было бы построить структуру директорий проекта, перед переходом к обсуждению (или реализации) логики приложения с использованием фреймворка. Алсо, как у тебя с доктриной прогресс?

**Comment by kubk** [comment]
Если вынести логику обновления тредов в сервис, то в консольном скрипте незачем иметь экземпляр Application. Или Application нужен в консольных скриптах по другой причине?
Обычно консольные скрипты просто используют сервисы из контейнера, к примеру в Symfony даже есть класс для этих целей: https://symfony.com/doc/current/console.html#getting-services-from-the-service-container
Ещё сервис проще тестировать в изоляции.
Касательно директорий, то, как мне кажется, подойдёт любая структура. С фреймворком выйдет немного классов.
Я могу помочь с написанием парсеров для старых тредов.

**Comment by someApprentice** [comment]
Я даже не мечтал о такой поддержке.
Спасибо, это очень много значит для меня.

**Comment by foobar1643** [comment]
@kubk Идея была в том, чтобы сделать один исполняемый файл, который в зависимости от переданных параметров будет использовать нужный сервис (хотя, если посмотреть на объем исполняемых файлов, их будет штуки 2 - 3, так что моя идея наверное не имеет смысла в нашем случае, это только переусложнение). Да и вроде как роутер слима это не поддерживает. Как будет свободное время, я потестирую и отпишу результаты.

> Касательно директорий, то, как мне кажется, подойдёт любая структура. Там же мало классов будет, если использовать фреймворк.

Если на проекте работает несколько разработчиков, лучше иметь какой-нибудь документ, в котором описывается структура директорий, которую прочитали и утвердили все, кто работает. Это чтобы избежать ситуаций, когда два человека создают файлы с общим назначением в разных директориях.

> Я могу помочь с написанием парсеров для старых тредов.

Вот это интересная штука. Тут сложность зависит от того, насколько часто и сильно менялась верстка в тредах (учитывая что треды существуют уже года три точно). Мне интересно как это можно сделать максимально гибко (без создания отдельного сервиса-парсера под каждый вариант). Тут можно было бы применить [стратегию](https://en.wikipedia.org/wiki/Strategy_pattern), но мне интересно как ты это видишь?

**Comment by kubk** [comment]
@foobar1643 понял насчёт директорий, тогда [такая структура](https://github.com/foobar1643/filehosting/tree/master/app), как мне кажется, подойдёт. Как раз контейнер инициализируется отдельно от приложения.

> Тут сложность зависит от того, насколько часто и сильно менялась верстка в тредах 

Да, вот примеры html для поста из [17-го](https://pastebin.com/NGGERVqK) треда и [71-го](https://pastebin.com/C6NXxw3n). Однако по очень оптимистичному предположению должно хватить XPath-запросов для всех тредов (XPath более мощный, чем CSS-селекторы). Получилось написать универсальные запросы для получения постов и их авторов (правда тестировал пока только на тредах 1-17 и 60-77), но обещать пока что-то сложно.
