### ISSUE TITLE
Кэширование страниц

### ISSUE THREAD

**Issue by foobar1643** [someApprentice/phpClub#13]
Сейчас при каждом GET запросе у нас происходит выборка данных из БД, и на основе этой выборки мы строим HTML страницу для каждого треда. С учатом того что у нас данные в старых тредах не изменяются, это неоптимально и дает лишнюю загрузку на сервер. Нужно сделать кэширование страниц для тредов и кэширование для главной страницы. Кэшировать нужно готовый результат с версткой, который приложение отдает пользователю. Должен использоватся интерфейс для кэширования, совместимый с [PSR-6](http://www.php-fig.org/psr/psr-6/), отличной реализацией является [symfony/cache](https://github.com/symfony/cache). Для начала нужно сделать кэширование в файлы, затем добавить опциональную возможность использования memcached. Кэш должен быть один для каждого треда, независимо от пользователя. 

Также нужно не забывать очищать кэш если происходит обновление данных как для тредов, так и для главной страницы.

Еще можно кэшировать цепь ответов для ссылок (роут /pr/chain/{post:[0-9]+}).

**Comment by izac1** [comment]
Думаю можно кэш делать тогда когда идёт 1 запрос , можно даже кэшить не весь html а выборку из базы , при запуски скрипта (update.php) сбрасывать кэш.

**Comment by codedokode** [comment]
Для главной, есть еще альтернативный вариант - кешировать не всю страницу, а отдельные блоки (ОП пост + последние несколько постов). Тогда при добавлении нового треда не надо  будет перестраивать кеши для главной, второй страницы (если он есть) итд. Ну это конечно надо внимательнее смотреть на проект, я точно не знаю, как он там используется. Но для обычной имиджборды имеет смысл именно кешировать отдельные блоки, чтобы упростить инвалидацию. 

Есть еще другой вариант - посмотреть, можно ли сделать эффективную выборку нужных данных из БД (например за счет денормализации) - может быть, кеш и не потребуется. 

> тк html строиться на кэше твига

Там кеш в том смысле, что из twig-шаблона генерируется php-шаблон (который может затем закешироваться в OPCache) и затем выполняется этот шаблон, то есть это не кеш HTML или каких-то данных.

> можно даже кэшить не весь html ... выборку из базы

Вот тут я не смогу согласиться, так как в базе есть свой кеш в памяти, и вполне возможно что это дополнительное кеширование ничего не даст, а может даже замедлит скорость получения данных (в случае использования файлов). Это конечно зависит от того, какая конфигурация БД. Но на практике, если у вас не хайлоад и сервер не дохлый, то результат простого запроса особо кешировать смысла нет. База сама много чего кеширует в памяти (результаты запросов - в query cache, куски таблиц и индексов в innodb pool) и сама инвалидирует эти кеши. Соответственно стоит проверить, что вы не  занимаетесь дублированием того, что уже есть и работает. Но конечно, если это какой-то слабый хостинг с перегруженной БД, то ситуация может быть другой. 

> Еще можно кэшировать цепь ответов для ссылок

Тут стоит учитывать еще такой фактор: насколько этот кеш будет востребован? Там ведь тысячи постов, и если изредка кто-то будет запрашивать цепочку для одного, то может быть проще просто взять данные из БД, чем держать на диске или в кеше тысячи огромных записей, которые почти никогда не используются. 

А так, кеширование для редко меняющегося сайта конечно можно при желании сделать очень агрессивным - вплоть до того, что генерировать gzip-нутые HTML файлы, и отдавать нгинксом их напрямую. Там скорость отдачи будет очень хорошая. 

Сложный момент - это как кешировать треды. Там проблема в том, что они огромные, а любые кеши лучше всего работают с небольшим объемом данных. Плюс, кеширование полного HTML мешает нам добавлять какие-то индивидуальные для пользователей вещи. Но так как тут тред редко обновляется, то наверно такой кеш все же может принести выгоду. Стоит потестировать еще возможность сжимать его - HTML хорошо жмется, и иногда затраты (времени) на сжатие могут быть меньше, чем затраты на чтение с диска или получение из мемкеша через сокет.

**Comment by kubk** [comment]
Объясните пожалуйста, смысл вообще на главной выводить 3 последних поста для каждого треда? На архиваче например просто список тредов и это кажется логичней. От 3-х последних постов есть польза, когда в треды можно постить. Например человек, просматривая нулевую, по 3-м последним постам может примерно определить, что же обсуждается в данный момент в треде и по желанию присоединится к беседе. Нужно ли это для архива тредов? Искать что-то удобнее всё равно через поиск.

**Comment by someApprentice** [comment]
@kubk потому что потом будет возможность постить с помощью API. И делей на отправку, если соединение с бордой не удалось установить.

**Comment by izac1** [comment]
@codedokode  

> так как в базе есть свой кеш в памяти
имелось ввиду вообще избавиться от подключение к базе , юз кейс например ОП пост у нас не меняется, если его кешить это даст прирост , ибо мы не будет подключаться к БД подавать запрос ждать ответ и тд. То есть например вытягиваем ОП пост при первом просмотре страницы , далее его тянуть с базы вовсе не надо , а только считать с диска , а это куда быстрее чем через БД.

**Comment by codedokode** [comment]
@izac1 

> а только считать с диска , а это куда быстрее чем через БД.

Откуда такая информация? Я бы без тестов так не утверждал, да и зависит от ситуации. Одно дело - общая и перегруженная база на shared хостинге, другое дело - своя база на своем сервере.

**Comment by izac1** [comment]
@codedokode  своя база на своём , тестировал при написании плагина для yii2 динамический  слагов к странице , на странице с 20 слагами даже с кешем BD прирост был в 40-50%. Алсо покажите тесты обратного.

**Comment by izac1** [comment]
@codedokode  в любом случае что бы не быть голословным , сегодня собираюсь сделать кеш html , покажу скрины с кешем доктрины и без
