### ISSUE TITLE
Оптимизация MySQL запросов

### ISSUE THREAD

**Issue by foobar1643** [someApprentice/phpClub#14]
В проекте сейчас есть несколько неоптимальных мест, где запросы к БД делаются в цикле, когда можно было выбрать те же самые данные, только одним запросом. Нужно эти вещи оптимизировать.

https://github.com/someApprentice/phpClub/blob/master/src/Service/Searcher.php#L40 - Можно сделать через WHERE IN().

https://github.com/someApprentice/phpClub/blob/master/src/Service/Threader.php#L160 - Можно считать в том же запросе, который выбирает список тредов

Список не полный, если где-нибудь есть сомнительные места, лучше их отписывать в комменты.

**Comment by izac1** [comment]
По первому [pull requst](https://github.com/someApprentice/phpClub/pull/16)

**Comment by izac1** [comment]
По второму [pull requst](https://github.com/someApprentice/phpClub/pull/17)

**Comment by foobar1643** [comment]
Спасибо, нужно будет еще проверить насколько гидрация замедляет вывод тредов с 1000+ постами, но это уже другая задача.
