### ISSUE TITLE
Переработать выборку последних постов

### ISSUE THREAD

**Issue by someApprentice** [someApprentice/phpClub#20]
* Отсортировать посты по убыванию и выбрать LIMIT n, где n - количество последних постов
* Вывести полученные результаты с конца

**Comment by kubk** [comment]
Одно из предложений ОПа - денормализовать данные и хранить первый и 3 последних поста каждого треда в отдельной таблице (в проекте уже была реализация с использованием таблицы для 3-х последних постов). Объясню, что поменял:
- Можно обойтись без сущности LastPost. Тем более, что это не сущность, а ссылка (на Post). В маппинге, связывающим Thread и 3 последних поста, можно сослаться на уже существующую сущность Post, но изменить таблицу - использовать last_post вместо post: https://github.com/someApprentice/phpClub/blob/experimental/src/Entity/Thread.php#L27
- Тут: https://github.com/someApprentice/phpClub/blob/master/src/Service/Threader.php#L149+L179
ручной маппинг. Доктрина создана как раз для того, чтобы не гидрировать объекты самостоятельно. С настроенным маппингом можно использовать такой DQL: https://github.com/someApprentice/phpClub/blob/experimental/src/Repository/ThreadRepository.php#L19+L21
- Заметил, что тут https://github.com/someApprentice/phpClub/blob/master/src/Service/Threader.php#L153 используется функция COUNT(), но потом в шаблоне её результат нигде не используется. Так ли нам нужна информация о количестве постов? На 2ch.hk пошли ещё дальше - там зачем-то выводится информация о том, сколько постов пропущено и сколько из них с картинками. Не могу придумать, кому и зачем это нужно.
- Самое интересное - пагинация. Дело в том, что для главной страницы не подходит обычная offset/limit пагинация. Из-за того, что у треда не обязательно будут 3 последних поста - тред может быть только создали и там всего 1 пост. Вот примерный результат SQL запроса, который джойнит thread на last_post:

thread_id | post_id | text
--- | --- | ---
1013 | 1013 | Третий тред, ОП-пост
502 | 502 | Второй тред, ОП-пост
502 | 1010 | Второй тред
502 | 1011 | Второй тред
502 | 1012 | Второй тред
1 | 1 | Первый тред, ОП-пост
1 | 499 | Первый тред
1 | 500 | Первый тред
1 | 501 | Первый тред

Как видим, на один тред может приходится 1-4 строк, в зависимости от того, сколько в треде постов. Мы наперёд не знаем сколько постов в треде, вот почему пагинация, основанная на offset и limit здесь не подойдёт. Однако в Доктрине это предусмотрели: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/pagination.html

**Comment by kubk** [comment]
Вопрос - как отображать ссылки на страницы при пагинации? Мне не очень нравится подход с автоподгрузкой постов - страница разрастается, чтобы перейти к самой последней записи нужно постоянно прокручивать вниз. ИМХО самый адекватный - просто список страниц:
1 | 2 | [ 3 ] | 4 ... 10

**Comment by codedokode** [comment]
Я тут мимо проходил. Хотел поделиться парой мыслей и опытом работы с доктриной.

Во-первых (если вас беспокоит производительность), жадная загрузка (`SELECT a, b ...`) не всегда эффективнее чем загрузка `SELECT a` и потом ленивая подгрузка b. Зависит наверно от того, какие сущности используются (например, если a -> b относится как многие-к-одному), но я наблюдал такие случаи. Проверить можно только микробенчмарком. При написании бенчмарков с доктриной тоже надо учитывать подводные камни - первое обращение к сущности может вызвать генерацию прокси-классов, парсинг аннотаций (кешируются они или нет, зависит от конфигурации, от режима CLI/не CLI). Для решения проблемы можно прогнать бенчмарк 1 раз, очистить Entity Map `$em->clear()`, и прогнать бенчмарк второй раз (теперь с прогретыми кешами). При этом БД скорее всего будет отдавать результат из кеша запросов, и меряться по сути будет только затраченное доктриной время. Также, при написании бенчмарка надо учитывать, что Доктрина активно использует ленивую загрузку. Наример: 

```php
// не вызывает SQL-запрос, возвращает PersistentCollection по моему
$posts = $thread->getPosts();

// Может вызвать только запрос SELECT COUNT
echo count($posts);

// вызывает запрос на получение постов, но нет гарантий что 
// $post содержит все данные, а не только id (является прокси)
$post = $posts[0];

// теперь данные точно загружены
echo $post->getText();
```

Во-вторых, хитрый пагинатор из доктрины - он довольно сложный, и у меня доверия не вызывает. Возможно, что тут проще сделать выборку только Threads с пагинацией, а потом выбрать отдельным запросом приджойненные сущности (посты). А может, ленивая загрузка этих сущностей при обращении не занимает много времени и можно вообще не заморачиваться. Опять же, без теста не сказать.

То есть я хочу сказать, проверьте сначала простое решение, может быть сложное и не требуется на таких объемах данных. Простое в смысле "код, который быстрее всего написать".

Также, стоит учесть, что треды в архиве не обновляются - а значит, денормализация данных не вызвает проблем (так как данные не обновляются, не надо заморачиваться с обновление денормализованных полей). Это очень удобно. Можно например в базу прописывать номер каждому посту, повесить индекс на это поле и делать эффективные выборки по индексу, если такая задача возникнет. Можно делать агрессивное кеширование. То есть  не меняющиеся данные - это большое везение, можно сказать.

Ну и еще, если надо выводить большой список чего-то постранично, то LIMIT/OFFSET работает все медленнее по мере увеличения OFFSET. Тут я думаю, данных не так много, но если их вдруг будет много (наример, лента всех постов из всех тредов), то есть другие методы пагинации: http://use-the-index-luke.com/no-offset 

И напоследок. В принципе, мы не обязаны копировать интерфейс оригинального сайта как есть. Никто не запрещает, например, в архиве сделать один мегатред из всех постов или поменять что-то еще.

**Comment by izac1** [comment]
no-offset классно работает если у нас только кнопки дальше и назад , если это делать по страницам то я думаю придётся делать дополнительный запрос что бы рассчитать все след id для каждой страницы.

**Comment by codedokode** [comment]
Верно, no-offset не работает с номерами страниц (на реддите используется, в API ютуба для постраничной загрузки комментов тоже видел его). Но в архиве тредов посты не удаляются и не переставляются, потому можно просто сделать колонку с номером поста и использовать ее в индексе. Это если нужно, на 500 постах может и не требуется.

> то я думаю придётся делать дополнительный запрос что бы рассчитать все след id для каждой страницы.

Тогда проще использовать `LIMIT`.
