### ISSUE TITLE
Пользовательские репозитории Доктрины

### ISSUE THREAD

**Issue by kubk** [someApprentice/phpClub#23]
Рекомендуется создавать пользовательские репозитории для запросов к БД: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html#custom-repositories

Преимущества:
- Метод репозитория гораздо проще мокать, делается одной строкой в PHPUnit. Мок для EntityManager будет сложнее, так как нужно мокнуть сначала репозиторий, а потом возвращаемое значение метода репозитория.
- При росте приложения проще искать запросы, так как они логически сгруппированы по классам.
- Немного короче код, ``` $this->userRepository->find(...``` вместо ``` $this->em->getRepository('phpClub\Entity\User')->find(...```

**Comment by izac1** [comment]
Я так понимаю их используют в случае когда нужно вынести запросы с createQuery которые повторно используются , заменять их find я думаю не правильно

**Comment by kubk** [comment]
Не нужно find заменять. Достаточно отнаследовать репозиторий от EntityManager (в ссылке указан пример) и инжектить в сервисы этот репозиторий вместо EntityManager. Например, [этот](https://github.com/someApprentice/phpClub/blob/master/src/Service/Authorizer.php) класс работает только с сущностью User. Но классу Authorizer незачем инжектить EntityManager, который по сути является точкой доступа ко всем сущностям в проекте.

**Comment by izac1** [comment]
Попробовал с Thread сервисом, правильно или нет ?

Создал в src папку Repository сделал файл ThreadRepository.php
`<?php
namespace phpClub\Repository;

use Doctrine\ORM\EntityRepository;

class ThreadRepository extends EntityRepository
{
	
}`

в сервисе заменил конструктор на 
`public function __construct(EntityRepository $threadRepository, Authorizer $authorizer)
    {
        //$this->em = $em;
        $this->threadRepository = $threadRepository;

        $this->authorizer = $authorizer;
    }`

и поправил в бутстрапе 

`$di['Threader'] = function (Container $di): Threader {
    return new Threader($di->get('EntityManager')->getRepository('phpClub\Entity\Thread'), $di->get('Authorizer'));
};`

**Comment by kubk** [comment]
@izac1 во втором листинге конструктор первым аргументом принимает EntityRepository, должен быть ThreadRepository (нам ведь нужен какой-то конкретный репозиторий, а не любой). Глядя на третий листинг, вспомнил, что большие фреймворки с умными DI-контейнерами очень сильно упрощают регистрацию сервисов: в Laravel достаточно было бы просто создать класс-репозиторий и в Threader добавить репозиторий как зависимость: https://laravel.com/docs/5.4/container#introduction
Нужен ли нам такой контейнер - вопрос спорный.

**Comment by izac1** [comment]
@kubk Функция `$di->get('EntityManager')->getRepository('phpClub\Entity\Thread')`
возвращает нам Doctrine\ORM\EntityRepository посему такую при проверке на phpClub\Repository\ThreadRepository ошибка 

> Argument 1 passed to phpClub\Service\Threader::__construct() must be an instance of phpClub\Repository\ThreadRepository, instance of Doctrine\ORM\EntityRepository given, called in E:\web_new\OpenServer\domains\phpthread\src\Bootstrap.php on line 65

**Comment by kubk** [comment]
@izac1это нормально, в документации написано: "By default the EntityManager returns a default implementation of Doctrine\ORM\EntityRepository when you call EntityManager#getRepository($entityClass). You can overwrite this behaviour ..." 
Короче в аннотациях сущности нужно указывать репозиторий, как тут: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html#custom-repositories
```php
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="MyDomain\Model\UserRepository")
 */
class User
{
}
```
Кстати вместо 
```php
$di->get('EntityManager')->getRepository('phpClub\Entity\Thread')
```
можно писать
```php
$di->get('EntityManager')->getRepository(Thread::class)
 ```
, предварительно импортировав неймспейс (IDE сама это сделает).

**Comment by izac1** [comment]
Ну если имеется ввиду сущность это Entity то так и есть Entity\Thread
```php
use Doctrine\ORM\Mapping as ORM;

/**
* @Entity @Table(name="threads")
* @ORM\Entity(repositoryClass="phpClub\Repository\ThreadRepository")
**/
```
Всё равно ошибка

**Comment by izac1** [comment]
Разобрался , нужно было почистить кеш мето данных

**Comment by izac1** [comment]
Как быть с теми методами там где 
`$this->em->persist($entity)`
`$this->em->flush()`

переопределять их в репозитории ?

**Comment by kubk** [comment]
@izac1 хороший вопрос, на который у меня нет однозначно верного ответа. [И не только у меня](https://habrahabr.ru/post/334776/#comment_10343668).
Предлагаю почитать статью: http://www.elisdn.ru/blog/108/domain-entities-doctrine (самое доступное чтиво по Doctrine, Unit of Work, IdentityMap на русском). Достаточно почитать до раздела "Установка".
Persistence-like репозитории я видел в реальных проектах, их же и предлагаю использовать. Чтобы не копипастить метод save, предлагаю вынести его в [базовый класс](https://github.com/kubk/symfony-bookshelf/blob/heroku/src/AppBundle/Repository/EntityRepository.php)
Туда же можно поместить создание стороннего пагинатора (встроенный в Доктрину не умеет генерировать HTML-код пагинации).

Но вообще save() в репозитории это не самая лучшая практика, так как репозиторий становится по сути TableDataGateway. Другое дело, что такая практика отлично работает даже для сложных приложений, с необходимостью [Persistence Ignorance](https://stackoverflow.com/a/906094) я пока не сталкивался.

**Comment by izac1** [comment]
@kubk В некоторых местах нам нужно делать просто flush я думаю тогда имеет смысл отделить их в базовом классе отдельно. В установке так нечего интересного не нашёл , но статься интересная.

**Comment by kubk** [comment]
По-хорошему репозиторий Доктрины не должен сохранять что-то в базу, это ответственность EntityManager - следить за изменениями в объектах и маппить это на БД. В этом вообще суть Доктрины - создать видимость, что мы работаем с объектами из мира ООП, а как это всё хранится - дело десятое. Процитирую пользователя fesor с хабра: "Когда в вашем репозитории появляется метод save или update то он перестает быть репозиторием и становится TableGateway который "вытек" из слоя персистентности в бизнес логику."
И вот ещё есть слайды с доклада "Save your repositories from save": https://www.slideshare.net/Yaboomaster1/save-repository-from-save
Автор сначала предлагает flush'ить всё в контроллере (EntityManager по-прежнему ни в какие сервисы не инжектится), а потом показывает пример middleware, который будет автоматом делать flush. Для чего всё это? Чтобы логика приложения не зависела от персистентного слоя и мы могли его легко менять. Надо ли это нам? Нет, мне вообще сложно придумать пример, где нужно будет часто менять хранилище данных.
Я считаю, что для phpClub это настоящий оверинжениринг. Идея issue изначально была только в том, чтобы логически сгруппировать запросы к БД и упростить тестирование в будущем. Сохранять сущности в БД можно по-разному - добавить в репозиторий метод для вставки в БД (видел в реальных проектах), можно flush'ить в контроллере (более правильный с точки зрения Доктрины метод).

**Comment by kubk** [comment]
@izac1 если тут https://github.com/someApprentice/phpClub/commit/fc3f364d013d65d9996b7ed656ba6e7bac4f5ea8 всё работает, то issue можно закрывать.

**Comment by izac1** [comment]
@kubk Если у кого-то есть возможность проверить Searcher и Linker сервисы на работоспособность  , то можно закрывать , ибо я проверил всё остальные работают.

**Comment by kubk** [comment]
@someApprentice можешь поиск проверить? Я со сфинксом не работал.
