### ISSUE TITLE
Замена "цепочки постов" на "избранные посты" или использование её для получения списка ответов?

### ISSUE THREAD

**Issue by someApprentice** [someApprentice/phpClub#28]
Небольшое предисловие:
> Я вообще хочу убрать эту функцию. Я когда проектировал, хотел чтобы обсуждения, которые растягиваются на несколько тредов, вывелись по одному клику. Но вместо этого, если в цепочку попадает ОП-пост или ещё какой-нибудь пост с кучей ответов, то всё превращается в кучу молу.
>За место этого, я хочу сделать, чтобы пользователи сами добавляли нужные им посты в "Избранное". Всё равно я планирую прикрутить чатик, поэтому регистрация в любом случае понадобиться.

Перед тем как начать переработку фронтенда, я бы хотел обсудить пару идей

Во-первых, это использовать _Избранное_ вместо _Цепочки ответов_

Во-вторых, можно оставить функцию получение _цепочки_(, но не выставлять её в интерфейс сайта), и использовать для получения ответов средствами php, а не js, что понизит нагрузку на клиент

**Comment by kubk** [comment]
Как по мне, цепочки - удобная штука. Избранное - тоже.

В таблице ref_link будет под миллион записей, если исходить из расчёта 8-10k записей на тред. Это не много + у нас выборка простая и кладётся на индексы: https://github.com/someApprentice/phpClub/blob/experimental/src/Service/RefLinkManager.php#L83

> и использовать для получения ответов средствами php, а не js, что понизит нагрузку на клиент
Клинет у нас и так разгружен будет полностью, а вот доктрина не любит такие большие выборки с джойнами. Но подход с PHP мне нравится больше, так как тогда у не возникнет несогласованность между цепочкой, которую построил JS-скрипт и тем, что находится в таблице ref_link

**Comment by kubk** [comment]
Пока что цепочки генерируются только для тредов 80+

Для старых тредов нужно менять регулярку: https://github.com/someApprentice/phpClub/blob/experimental/src/ThreadImport/RefLinkGenerator.php#L69

**Comment by codedokode** [comment]
Насчет выборки, вы вообще не обязаны выбирать данные только через Доктрину. Если вам, условно говоря, нужны только связи между постами из таблицы, вполне допустимо их просто выбрать SQL запросом. То есть, иногда проще использовать SQL напрямую. Особенно, когда надо посчитать количество чего-то или выбрать только id-шники.

Цепочки имхо полезная фича, на оригинальной борде, когда цепочка длинная, мышкой открывать ее не очень удобно.

ОП посты можно пропускать.

**Comment by kubk** [comment]
Согласен. Думаю обсуждение можно закрывать.
