### ISSUE TITLE
Предложение: не создавать кеш для каждого пользователя

### ISSUE THREAD

**Issue by codedokode** [someApprentice/phpClub#31]
Вот тут вот https://github.com/someApprentice/phpClub/blob/master/src/Controller/BoardController.php#L102 есть такой код: 

```php
        $template = $this->getOrSetCache('/chain.phtml', [
            'posts' => $chain,
            'logged' => $this->authorizer->isLoggedIn()],
            'chain' . (int) $args['post'] .'_' . ($this->authorizer->isLoggedIn() ? $_COOKIE['token'] : false)
        );
```

Создавать свой кеш для каждого пользователя не очень эффективно, тем более, если это дисковый кеш, и это плохо масштабируется с ростом числа пользователей. Обычно либо не делают кеш для залогиненных пользователей вообще, либо кешируют не на уровне HTML (условно говоря, можно было бы кешировать массив сущностей Доктрины). Если поиск постов в цепочке не занимает много времени, то, скорее всего, кеширование здесь может вообще не требоваться.  

Также, кеш лучше не создавать для крошечных цепочек или цепочек из одного поста. Так как поисковые роботы не поленятся кликнуть на каждую ссылку Chain на сайте и будет создано огромное количество ключей кеша. Маленькие цепочки скорее всего и без кеша быстро генерируются.

**Comment by kubk** [comment]
Сейчас цепочки генерируются один раз при импорте треда, не вижу смысла вообще их кешировать, их очень много.
Ещё вопрос - если на сайте появятся "избранные" посты, то выходит, что и от кеша для треда придётся отказаться. Так как тогда возле каждого поста нужно добавить звёздочку либо ссылку "добавить в избранное/убрать из избранного".

**Comment by codedokode** [comment]
Избранное работает (я так думаю) только для части пользователей -  значит анонимные пользователи без избранного могут продолжать использовать кеш. А так да, либо отказываться от кеша, либо яваскриптом модифицировать страницу после загрузки, как это сделано на 2ch.

**Comment by someApprentice** [comment]
Проблема с кешированием цепочек уже обсуждалась, но @izac1 всё равно решил его добавить

Я поддерживаю это предложение

**Comment by someApprentice** [comment]
> либо яваскриптом модифицировать страницу после загрузки

Что если яваскрипт будет отключен у пользователя? Останется только решение с отключением кеша. 

Или, возможно ли будет оставить кэш только для не залогиненных пользователей? И будет ли это востребовано?

**Comment by codedokode** [comment]
> Что если яваскрипт будет отключен у пользователя?

Как вариант, можно не поддерживать закладки без JS. Ну или отказаться  от HTML-кеша для пользователей с закладками. 

> Или, возможно ли будет оставить кэш только для не залогиненных пользователей? И будет ли это востребовано?

Так делают очень часто, кеш используется только для анонимов. Но конечно надо понимать, что HTML-кеш это по большому счету костыль, когда у нас нет других способов ускорить код (или когда это несет слишком большие трудозатраты).

**Comment by kubk** [comment]
Закладки без JS очень неудобно. Предположим, что я хочу добавить 3 поста подряд в избранное. С JS-ом я просто кликну на 3 звёздочки, без JS у нас есть несколько неудобных способов:
- после каждого добавления поста в избранное перезагружать тред (мы ведь следуем https://en.wikipedia.org/wiki/Post/Redirect/Get ?)
- выделять с помощью чекбокса пачку постов и только потом делать Post/Redirect/Get. Всё равно неудобно для пользователя.

Любители отключать JS могут добавить фильтр для сайта. Майнеров мы никаких ставить не будем.

**Comment by codedokode** [comment]
Я сам сторонник, чтобы все по максимуму работало без JS (это очень помогает на плохих соединениях, например), но с закладками, наверно нет смысла так сильно заморачиваться. Для добавления закладок вполне можно требовать наличие JS.

**Comment by kubk** [comment]
Let's summarize!

- Кеш цепочек убираем, так как цепочек будет очень много
- Кеш тредов и главной страницы оставляем только для не авторизованных пользователей

В будущем добавим "избранное" с использованием JS
