### ISSUE TITLE
Ссылки на посты не работают на главной

### ISSUE THREAD

**Issue by codedokode** [someApprentice/phpClub#32]
Если открыть https://phpclub.tech/ и нажать любую ссылку вида >>XXX, то получаем URL вида https://phpclub.tech/#977782 , который никуда не ведет. Ссылки можно выводить в формате #XXX только если они относятся к открытому на текущей странице треду, а в остальных случаях надо формировать полноценный URL с указанием треда.

**Comment by someApprentice** [comment]
Да, там этой проблеме будет самое место

В дополнению к этому, не будет ли затруднительно обработать ссылки таким образом, чтобы в старых тредах содержали атрибуты такие же как и в новых?
Нужно в старых убрать атрибуты onmouseover="...", onmouseout="...",  onclick="...", а заместо них добавить class="post-reply-link" data-thread="..." data-num="...", и в href="..." добавить абсолютную ссылку (/pr/res/....html#...)

**Comment by kubk** [comment]
@someApprentice Ох, сложно это. Там же в посте частенько код постят, нужно как-то не задеть его. ID треда и поста мы можем в HTML генерить, у нас ведь есть контроль над генерацией HTML: https://github.com/someApprentice/phpClub/blob/master/templates/post.phtml

А при изменении старых постов легко допустить ошибку и вырезать лишнее.

**Comment by someApprentice** [comment]
@kubk можно воспользоваться такой регуляркой: https://regex101.com/r/Ze34Tl/2
2-ую, 3-тью и 6-ую подмаску удалить, если есть 4-ая, то заменить её на нашу ссылку (или просто обрезать на относительную ссылку), иначе к 5-ой добавить относительную ссылку (предварительно передав сущность Post, которую мы собираемся отредактировать), и в конец добавить атрибуты  class="post-reply-link" data-thread="..." data-num="..."

>Ну и мне опять не нравится именование - что значит num? Гораздо лучше post-id
Это именование атрибутов из ссылок на посты в текущей версии 2ch.hk

**Comment by codedokode** [comment]
Вообще, идеальнее всего было бы убирать теги `<a>` из источника, и генерировать их заново по нужным нам правилам. Но не знаю, как это в плане сложности.

**Comment by someApprentice** [comment]
Ссылки на посты спаршенные с архивача, которые ссылаются на другой тред ссылаются на не  существующее (для нас) API
`<a href="/ajax/?act=locate_thread&url=https://2ch.hk/pr/res/1097438.html" class="post-reply-link" data-thread="1097438" data-num="1097438">>>1097438 (OP)</a>`
