### ISSUE TITLE
Улучшение обратной связи парсера

### ISSUE THREAD

**Issue by foobar1643** [someApprentice/phpClub#5]
Плохо что в парсере нет никаких прогресс-баров и сообщений. У меня на виртуалке он провисел минут 20, мне приходилось лезть в базу для того чтобы понять, он все еще работает или завис. Тут есть множество вариантов реализации, у Symfony/Console, например есть хороший прогресс-бар, но если есть проблемы с его использованием, можно хотя бы выводить в консоль имена тредов когда начинается их парсинг, например:

```
Parsing thread number: 966608
Parsing thread number: 978987

```

Затем можно добавить сообщения о том что парсер еще жив, например когда он распарсил 25%, 50% и 75% треда (с реализацией же не будет проблем?).

Сообщение приведено как пример, если решим делать, нужно будет что-нибудь информативнее.

**Comment by kubk** [comment]
Да, я как раз использую symfony/console + PSR логгер. То есть логгер пишет сообщения с разным уровнем verbosity, а пользователь уже сам выберает какие ему видеть, указывая константы из OutputInterface: http://api.symfony.com/2.7/Symfony/Component/Console/Output/OutputInterface.html
Как это выглядит сейчас:
```php
use Symfony\Component\Console\Logger\ConsoleLogger;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Output\OutputInterface;

$verbosity = OutputInterface::VERBOSITY_NORMAL; // В консоль писать только ошибки
$verbosity = OutputInterface::VERBOSITY_VERY_VERBOSE; // Полный отчёт о каждом посте
$logger =  new ConsoleLogger(new ConsoleOutput($verbosity);
$threadParser = new ThreadParser($logger, /* остальные зависимости */);
```

**Comment by foobar1643** [comment]
@kubk Интересно было бы посмотреть на твою реализацию парсера, и по её подобию переделать уже существующий парсер тредов, потому что он сделан не очень хорошо. Почему не коммитишь? Для разработки можно отдельную ветку сделать

**Comment by kubk** [comment]
@foobar1643 Существующий парсер маппит JSON на объекты доктрины и сохраняет всё в базу. У меня другая ответственность - разобрать HTML и предоставить информацию о постах в удобном для манипуляции виде. Какие могут быть манипуляции? Например, ОП предлагает при сохранении тредов строить для каждого поста список всех достижимых узлов: https://2ch.hk/pr/res/966608.html#974518
И кто знает, какие манипуляции могут понадобиться в будущем. Поэтому мне кажется логичным разделить парсинг (извлечение постов из HTML) и сохранение постов. Сейчас парсер отдаёт информацию примерно в таком виде:
```
12 => [
    "author" => "Аноним",
    "date" => "Суб 01 Фев 2014 13:38:30 ",
    "id" => "322554",
    "text" => "<a onmouseover="showPostPreview(event)" onmouseout="delPostPreview(event)" href="#322551" onclick="highlight(322551)">&gt;&gt;322551</a><br>Я ожидал увиделать ошибку в окне фаерфокса, но ее там нет. Зато нашел в error.log Нужно как - то перекинуть ее, в фаерфокс.<br><br>Sat Feb 01 12:24:59.824826 2014] [:error] [pid 2442] [client 127.0.0.1:40561] PHP Parse error:  syntax error, unexpected '}' in /var/www/oop.php on line 10",
    "files" => [],
13 => [
    "author" => "Аноним",
...
```
То есть массив массивов. Почему не сразу на объекты доктрины? Потому что они скорее всего будут меняться, как и способ маппинга, а к парсингу HTML это никакого отношения не имеет (тут я вспомнил про "У класса должна быть только одна причина для изменения").
@foobar1643 , @someApprentice Как вы на это смотрите?

Не коммичу, потому что парсер на 100% не готов :) 
Но теперь потороплюсь, раз нужно.

**Comment by foobar1643** [comment]
@kubk Я думаю этот способ хороший, я бы и парсинг JSON сделал таким же способом.

Про версию PHP кстати не знаю, потому что у меня пока нет возможности предоставлять хостинг. Нужно уточнить у @someApprentice какую версию поддерживает его хостер, потому что я новую структуру делал на 7.1.

**Comment by someApprentice** [comment]
@kubk Когда ещё ты описал этот способ по почте, мне сразу это показалось отличной идей.

@foobar1643 Версия PHP 7.0.15.

**Comment by kubk** [comment]
Добавил progress bar symfony: https://github.com/someApprentice/phpClub/blob/experimental/src/ThreadParser/Command/ImportThreadsCommand.php#L45
