### ISSUE TITLE
Заглушка если еще не добавлено ни одного треда

### ISSUE THREAD

**Issue by foobar1643** [someApprentice/phpClub#6]
Сейчас если в БД нет ни одного треда, в браузере показывается пустая страница с несколькими hr элементами и надписью phpClub.

Возможно стоит добавить какой-нибудь текст, который информирует о том, что в системе еще нет тредов (и ссылку на инструкцию как начать их добавлять)?

**Comment by foobar1643** [comment]
То же самое нужно сделать на странице поиска, когда не было ни одного результата.

**Comment by kubk** [comment]
https://github.com/someApprentice/phpClub/blob/master/templates/board.phtml#L32
